// farmshop-frontend/src/components/ProductList.vue
<script setup>
import { ref, onMounted, computed } from 'vue'
import axios from 'axios'
import { useRouter } from 'vue-router'

const products = ref([])
const searchQuery = ref('')
const selectedCategory = ref('')
const router = useRouter()

const filteredProducts = computed(() => {
  const results = products.value.filter(p => {
    const matchesSearch = searchQuery.value.trim()
      ? p.name.toLowerCase().includes(searchQuery.value.toLowerCase())
      : true

    const matchesCategory = selectedCategory.value
      ? p.category === selectedCategory.value
      : true

    return matchesSearch && matchesCategory
  })

  console.log('🔍 Produits filtrés:', results.length ? results : 'Aucun produit trouvé')

  return results
})

onMounted(async () => {
  try {
    const response = await axios.get('http://localhost:8000/api/products/')
    console.log('✅ API Response:', response.data)
    products.value = response.data
  } catch (error) {
    console.error('❌ Erreur API:', error)
  }
})

const categories = computed(() => {
  const uniqueCategories = [...new Set(products.value.map(p => p.category))]
  return uniqueCategories
})

const viewProduct = (id) => {
  router.push(`/products/${id}`)
}
</script>

<template>
  <div class="container mt-4">
    <h2 class="mb-4">🌽 Nos produits</h2>

    <div class="row mb-4">
      <div class="col-md-6">
        <input type="text" v-model="searchQuery" class="form-control" placeholder="🔍 Rechercher un produit...">
      </div>
      <div class="col-md-6">
        <select v-model="selectedCategory" class="form-control">
          <option value="">Toutes les catégories</option>
          <option v-for="category in categories" :key="category">
            {{ category }}
          </option>
        </select>
      </div>
    </div>

    <!-- ✅ Vérification si des produits sont trouvés -->
    <div v-if="filteredProducts.length > 0" class="row">
      <div v-for="product in filteredProducts" :key="product.id" class="col-md-4 mb-4">
        <div class="card">
          <img :src="product.imageUrl" class="card-img-top" :alt="product.name">
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text"><strong>{{ product.price }}€</strong></p>
            <p class="card-text text-muted">{{ product.category }}</p>
            <button @click="viewProduct(product.id)" class="btn btn-primary">👁️ Voir plus</button>
          </div>
        </div>
      </div>
    </div>

    <!-- ✅ Message si aucun produit trouvé -->
    <div v-else class="alert alert-warning text-center mt-4">
      Aucun produit trouvé. Essayez un autre terme !
    </div>
  </div>
</template>

<style scoped>
.card-img-top {
  height: 200px;
  object-fit: cover;
}
</style>

// farmshop-frontend/src/app/components/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService } from '../../services/product.service'; // Import du service

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
  products: any[] = []; // Stocker les produits

  constructor(private productService: ProductService) {}

  ngOnInit(): void {
    this.loadProducts();
  }

  loadProducts(): void {
    this.productService.getProducts().subscribe(
      (data) => {
        this.products = data;
      },
      (error) => {
        console.error('Error fetching products:', error);
      }
    );
  }
}

<div class="container">
  <h2 class="text-center mt-4">Nos Produits</h2>

  <!-- ✅ Barre de recherche et filtre -->
  <div class="row mb-4">
    <div class="col-md-6">
      <input
        type="text"
        class="form-control"
        placeholder="Rechercher un produit..."
        [(ngModel)]="searchQuery"
        (input)="onSearch()">
    </div>

    <div class="col-md-6">
      <select class="form-control" [(ngModel)]="selectedCategory" (change)="onCategoryChange()">
        <option value="" selected>Toutes les catégories</option>
        <ng-container *ngFor="let category of categories; trackBy: trackByCategory">
          <option *ngIf="category !== 'Toutes les catégories'" [value]="category">
            {{ category }}
          </option>
        </ng-container>
      </select>
    </div>
  </div>

  <!-- ✅ Carrousel des produits -->
  <div class="carousel-container">
    <button class="slider-btn left" (click)="scrollLeft()">❮</button>

    <div class="carousel-wrapper" #productSlider>
      <div class="product-card" *ngFor="let product of filteredProducts; trackBy: trackByProduct">
        <img [src]="product.imageUrl" class="product-img" [alt]="product.name">
        <div class="product-info">
          <h5>{{ product.name }}</h5>
          <p><strong>{{ product.price }}€</strong></p>
          <p class="text-muted">{{ product.category }}</p>
          <button class="btn btn-primary" (click)="viewProductDetails(product.id)">Voir plus</button>
        </div>
      </div>
    </div>

    <button class="slider-btn right" (click)="scrollRight()">❯</button>
  </div>

  <!-- ✅ Message si aucun produit trouvé -->
  <div *ngIf="filteredProducts.length === 0" class="text-center mt-4">
    <p class="alert alert-warning">Aucun produit trouvé.</p>
  </div>
</div>
